const {chromium} = require('playwright');
const {spawn,execFileSync} = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname,'..');
const php = process.env.PHP_BINARY || 'C:/xampp/php/php.exe';
const artifacts = path.resolve(root,'../../../.codex-tmp/personalization');
fs.mkdirSync(artifacts,{recursive:true});
const env = {...process.env,DB_NAME:'neo_personalization_ui_'+process.pid,DB_AUTO_CREATE:'true',DB_AUTO_MIGRATE:'true'};
const fixture = (...args) => execFileSync(php,[path.join(__dirname,'personalization-browser-fixture.php'),...args],{cwd:root,env,encoding:'utf8'});
const origin = 'http://127.0.0.1:8791';
let server, browser, mainPage;
(async()=>{
 fixture('setup');
 server=spawn(php,['-d','session.save_path='+artifacts,'-S','127.0.0.1:8791','-t',root],{cwd:root,env,windowsHide:true,stdio:['ignore','ignore','pipe']});
 let logs=''; server.stderr.on('data',c=>{logs+=c;});
 for(let i=0;i<60;i++){try{const r=await fetch(origin+'/onboarding-api.php');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,channel:'msedge'});
 const context=await browser.newContext({viewport:{width:1440,height:900}});
 const page=await context.newPage(); mainPage=page; const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/register.php');
 await page.waitForFunction(()=>document.querySelector('.neo-intro-overlay.parent-curtain-open'));
 await page.waitForTimeout(620);
 const introState=await page.evaluate(()=>{
  const overlay=document.querySelector('.neo-intro-overlay');
  const iframe=overlay.querySelector('iframe');
  return {overlayBackground:getComputedStyle(overlay).backgroundColor,iframeBackground:getComputedStyle(iframe).backgroundColor,iframeOpacity:getComputedStyle(iframe).opacity};
 });
 assert.equal(introState.overlayBackground,'rgba(0, 0, 0, 0)','intro opens over the Manel screen');
 assert.equal(introState.iframeBackground,'rgba(0, 0, 0, 0)','opening stays transparent');
 assert.equal(introState.iframeOpacity,'0','completed logo frame leaves before the page curtain opens');
 const stage=page.locator('#neo-setup-stage');
 await page.locator('[data-neo-companion]').waitFor();
 const initialFace=await page.locator('[data-neo-companion]').boundingBox();
 assert(initialFace.width>200&&initialFace.height>120,'Manel starts large before greeting');
 await page.locator('.neo-setup.has-studies').waitFor();
 const dockedFace=await page.locator('[data-neo-companion]').boundingBox();
 const shellBox=await page.locator('.study-shell').boundingBox();
  assert(dockedFace.width<=100&&dockedFace.height<=80&&dockedFace.x<shellBox.x+120&&dockedFace.y<shellBox.y+120,'Manel docks small in the upper left');
  await page.screenshot({path:path.join(artifacts,'1440-welcome.png')});
  await page.waitForFunction(()=>document.querySelectorAll('#neo-setup-stage > .neo-setup-assistant').length===2);
  const firstGreetingMinOpacity=await page.evaluate(()=>new Promise(resolve=>{
   const stage=document.querySelector('#neo-setup-stage');const first=stage.querySelector('.neo-setup-assistant');let minimum=1;const deadline=performance.now()+2500;
   function sample(){minimum=Math.min(minimum,Number.parseFloat(getComputedStyle(first).opacity)||0);if(!stage.classList.contains('is-manel-typing')||performance.now()>deadline){resolve(minimum);return;}requestAnimationFrame(sample);}sample();
  }));
  assert(firstGreetingMinOpacity>.98,'The first greeting must stay stable while the second message appears');
  if(process.env.ONBOARDING_INTRO_ONLY==='1'){assert.deepEqual(errors,[]);console.log('PASS: onboarding greetings transition without blinking.');return;}
  const apiState=await (await page.request.get(origin+'/onboarding-api.php')).json();
 assert.equal(apiState.authenticated,false);
 const post=(body)=>page.request.post(origin+'/onboarding-api.php',{data:{...body,csrf_token:apiState.csrf_token}});
 assert.equal((await page.request.post(origin+'/onboarding-api.php',{data:{action:'save',step:'nome',value:'Lara'}})).status(),419);
 assert.equal((await post({action:'finish',credentials:{email:'bypass@example.test',senha:'Neo-test-1234',confirmar_senha:'Neo-test-1234'}})).status(),422);
 assert.equal((await post({action:'save',step:'tempo',value:'30'})).status(),422);
 const step=async(id)=>{await page.waitForFunction(s=>document.querySelector('#neo-setup-stage')?.dataset.step===s,id);await page.waitForFunction(()=>document.querySelector('#neo-setup-stage')?.getAttribute('aria-busy')!=='true');};
 const choose=async(id,value,next)=>{await step(id);await stage.locator('input[value="'+value+'"]').check();if(next)await step(next);};
 const proceed=async(selector='input:not([type=checkbox]):not([type=radio])')=>stage.locator(selector).last().press('Enter');
 await page.waitForFunction(()=>document.querySelector('#neo-setup-stage.is-manel-typing'));
 assert(await page.locator('[data-neo-companion]').evaluate(el=>el.classList.contains('is-study-talking')),'Manel speaks while typing the question');
 assert.equal(await stage.locator('form').isVisible(),false,'Answer stays hidden until Manel finishes speaking');
 assert.equal(await stage.locator('.neo-setup-speaker').count(),0,'Question bubble has no Manel label');
 assert.equal(await stage.locator('.neo-setup-assistant > p:not(.neo-setup-subcount)').count(),0,'Question bubble has no auxiliary message');
 const assistantMargins=await stage.locator('.neo-setup-assistant').evaluate(el=>{const css=getComputedStyle(el);return [css.marginLeft,css.marginRight];});
 assert.equal(assistantMargins[0],assistantMargins[1],'Question bubble has equal horizontal margins');
 await page.screenshot({path:path.join(artifacts,'1440-typing.png')});
 await step('nome');
 const replyMargins=await stage.locator('.neo-setup-reply').evaluate(el=>{const css=getComputedStyle(el);return [css.marginLeft,css.marginRight];});
 assert.deepEqual(replyMargins,assistantMargins,'Answer and question bubbles use the same horizontal margins');
 assert.equal(await stage.locator('.neo-setup-reply-title,.neo-setup-field > span,.neo-setup-choice small,.neo-setup-actions').count(),0,'Question responses have no small labels or navigation actions');
 await stage.locator('[name=nome]').fill('asdfgh');await proceed('[name=nome]');
 await page.locator('#neo-setup-feedback:not([hidden])').waitFor();assert.equal(await stage.getAttribute('data-step'),'nome');
 await stage.locator('[name=nome]').fill('Lara');
 assert(await page.locator('[data-neo-companion]').evaluate(el=>el.classList.contains('is-thinking')));
 await proceed('[name=nome]');await step('gostos');
 await page.getByRole('button',{name:/Voltar/}).click();await step('nome');assert.equal(await stage.locator('[name=nome]').inputValue(),'Lara');await proceed('[name=nome]');await step('gostos');
 await stage.locator('input[value="jogos"]').check();await stage.locator('input[value="musica"]').check();await page.getByRole('button',{name:/Seguinte/}).click();await step('ensino');
 await page.reload();await step('nome');assert.equal(await stage.locator('[name=nome]').inputValue(),'','Reload must restart registration at the first empty answer');
 await stage.locator('[name=nome]').fill('Lara');await proceed('[name=nome]');await step('gostos');
 await stage.locator('input[value="jogos"]').check();await stage.locator('input[value="musica"]').check();await page.getByRole('button',{name:/Seguinte/}).click();await step('ensino');
 await choose('ensino','medio','modo');await choose('modo','personalizado','materias');
 await stage.locator('input[value="matematica"]').check();await page.getByRole('button',{name:/Seguinte/}).click();await step('objetivo');await choose('objetivo','enem','meta');
 await choose('meta','nao','niveis');await stage.locator('input[value="basico"]').check();await step('formatos');
 await stage.locator('input[value="questoes"]').check();await stage.locator('input[value="resumos"]').check();await page.getByRole('button',{name:/Seguinte/}).click();await step('explicacao');
 await choose('explicacao','passo_a_passo','tempo');await choose('tempo','30','dias');
 await choose('dias','4','ritmo');await choose('ritmo','normal','gamificacao');
 await stage.locator('input[value="aprendizado"]').check();await page.getByRole('button',{name:/Seguinte/}).click();await step('motivacao');await choose('motivacao','diretas','resumo');
 assert.equal(await stage.locator('[data-edit-step]').count(),15);
 assert(page.url().endsWith('register.php'));
 await page.screenshot({path:path.join(artifacts,'1440-summary.png'),fullPage:true});
 await stage.getByRole('button',{name:/Prosseguir para o e-mail/}).click();await step('credentials');
 await stage.locator('[name=email]').fill('lara@example.test');await stage.locator('[name=senha]').fill('Neo-test-1234');await stage.locator('[name=confirmar_senha]').fill('Neo-test-1234');
 const storage=await page.evaluate(()=>JSON.stringify(localStorage));assert(!storage.includes('Neo-test-1234')&&!storage.includes('lara@example.test'));
 await stage.locator('[name=confirmar_senha]').press('Enter');await page.waitForURL('**/index.php');
 await page.locator('.personal-study-panel').waitFor();assert(await page.locator('body').evaluate(el=>el.classList.contains('neo-learning-focus')));
 await page.waitForFunction(()=>!document.body.classList.contains('neo-interface-locked'),null,{timeout:12000});
 await page.waitForTimeout(700);
 if(await page.locator('[data-manel-tour]:not([hidden])').count())await page.locator('[data-tour-skip]').click();
 assert.equal(await page.locator('.level-row').isVisible(),true);
 const profile=JSON.parse(fixture('profile','lara@example.test'));assert.equal(Number(profile.personalizacao_versao),1);assert.match(profile.gostos,/Jogos/);assert.match(profile.gostos,/Música/);const saved=JSON.parse(profile.personalizacao_json);assert.deepEqual(saved.gostos.selected,['jogos','musica']);assert.equal(saved.niveis.matematica,'basico');
 assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundImage),'none','The site uses a flat themed background without wallpaper');
 assert.match(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundAttachment),/^fixed(?:, fixed)*$/,'Global wallpaper remains fixed');
 assert.match(await page.locator('.shop-panel').evaluate(el=>getComputedStyle(el).backgroundImage),/store-banner-bg\.webp/,'Dashboard store button uses its optimized illustration');
 assert.equal(await page.locator('.mini-panel').count(),0,'Legacy dashboard statistic squares were removed');
 const dashboardLayout=await page.evaluate(()=>{const routine=document.querySelector('.personal-study-panel').getBoundingClientRect();const shop=document.querySelector('.shop-panel').getBoundingClientRect();const level=document.querySelector('.level-row').getBoundingClientRect();const recent=document.querySelector('.recent-panel').getBoundingClientRect();return{sameRow:Math.abs(routine.top-shop.top)<2,routineW:routine.width,shopW:shop.width,levelAfter:level.top>routine.bottom,recentAfter:recent.top>level.bottom};});
 assert(dashboardLayout.sameRow&&dashboardLayout.routineW>dashboardLayout.shopW&&dashboardLayout.levelAfter&&dashboardLayout.recentAfter,'Dashboard follows hero, experience and recent-access order');
 await page.locator('.shop-panel').hover();await page.waitForTimeout(220);
 const shopHover=await page.evaluate(()=>{const grid=document.querySelector('.dashboard-hero-grid').getBoundingClientRect();const shop=document.querySelector('.shop-panel').getBoundingClientRect();return{gridTop:grid.top,shopTop:shop.top};});
 assert(shopHover.shopTop>=shopHover.gridTop,'Store banner hover stays inside the visible top edge');
 await page.screenshot({path:path.join(artifacts,'1440-dashboard.png')});
 await page.locator('#sidebarToggle').click();
 const storeNav=page.locator('#sidebar a[href="loja.php"]');
 await storeNav.click();
 await page.waitForURL('**/loja.php');
 await page.locator('.store-heading').waitFor();
 assert.equal(await storeNav.getAttribute('aria-current'),'page','Store button is marked as the active sidebar destination');
 assert.match(await page.locator('.store-heading').evaluate(el=>getComputedStyle(el).backgroundImage),/store-banner-bg\.webp/,'Store banner uses its optimized illustration');
 await page.screenshot({path:path.join(artifacts,'1440-store.png')});
 await page.goto(origin+'/materias.php');
 const subjectItem=page.locator('.subject-item').first();
 await subjectItem.waitFor();
 assert.equal(await page.locator('.subject-actions').count(),0,'Old hover action menu was removed');
 await subjectItem.locator('.subject').hover();await page.waitForTimeout(180);
 const subjectHoverColors=await subjectItem.evaluate(el=>({icon:getComputedStyle(el.querySelector('.materia-icon')).color,star:getComputedStyle(el.querySelector('.icon-hover-star-core')).fill}));
 assert.equal(subjectHoverColors.star,subjectHoverColors.icon,'Subject hover star follows the subject color');
 await page.locator('[data-subject-add-open]').click();
 await page.locator('[data-subject-request-modal].is-open').waitFor();
 await page.locator('.subject-request-submit').hover();await page.waitForTimeout(180);
 assert.equal(await page.locator('.subject-request-submit .icon-hover-star-core').evaluate(el=>getComputedStyle(el).fill),'rgb(26, 46, 255)','Add-subject modal uses the NEO blue hover star');
 await page.locator('.subject-request-close').click();
 await page.locator('[data-subject-request-modal]').waitFor({state:'hidden'});
 const deleteToggle=page.locator('[data-subject-delete-toggle]');
 await deleteToggle.click();
 assert(await page.locator('body').evaluate(el=>el.classList.contains('subject-delete-mode')),'Trash card enables multi-selection mode');
 await subjectItem.locator('.subject').click();
 assert(await subjectItem.evaluate(el=>el.classList.contains('is-selected')),'Subject icon can be selected without opening it');
 assert.match(await deleteToggle.locator('[data-delete-status]').innerText(),/1 selecionada/);
 await deleteToggle.click();
 await page.locator('[data-subject-delete-modal].is-open').waitFor();
 assert.equal(await page.locator('[data-subject-delete-inputs] input[name="materia_ids[]"]').count(),1,'Confirmation receives every selected subject');
 await page.locator('.subject-delete-confirm').hover();await page.waitForTimeout(180);
 assert.equal(await page.locator('.subject-delete-confirm .icon-hover-star-core').evaluate(el=>getComputedStyle(el).fill),'rgb(255, 59, 92)','Delete confirmation uses the red hover star');
 await page.waitForTimeout(240);
 await page.screenshot({path:path.join(artifacts,'1440-subject-delete.png')});
 await page.locator('[data-subject-delete-close]').last().click();
 const seeded=JSON.parse(fixture('questions'));
 await page.goto(origin+'/questoes.php?conteudo_id='+seeded.contentId);
 await page.waitForFunction(()=>!document.body.classList.contains('neo-interface-locked'));
 for(const [index,radio] of (await page.locator('.question-form .question-card').all()).entries())await radio.locator('input[value="'+(index<3?'A':'B')+'"]').check();
 await page.locator('.question-submit').click();await page.locator('.result-panel').waitFor();
 await page.goto(origin+'/aprendizado.php');assert((await page.locator('body').innerText()).includes('Caderno de erros'));assert.equal(await page.locator('.learning-error').count(),2);
 await page.locator('#examType').selectOption('conteudo');await page.locator('[name=conteudo_id]').selectOption(String(seeded.contentId));await page.locator('[name=quantidade]').fill('5');
 await page.getByRole('button',{name:/Preparar meu simulado/}).click();await page.locator('#learningExam').waitFor();
 for(const q of await page.locator('#learningExam [data-question]').all())await q.locator('input[value=A]').check();
 await page.getByRole('button',{name:/Concluir e ver meu resultado/}).click();await page.locator('.learning-result').waitFor();assert((await page.locator('.learning-result').innerText()).includes('5/5'));
 const before=await page.locator('.learning-result').innerText();await page.reload();assert.equal(await page.locator('.learning-result').innerText(),before);
 for(const width of [1440,390,320]){
   await page.setViewportSize({width,height:width===1440?900:844});await page.goto(origin+'/aprendizado.php');await page.waitForFunction(()=>!document.body.classList.contains('neo-interface-locked'));
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Learning page overflows '+width);
   await page.screenshot({path:path.join(artifacts,width+'-learning.png'),fullPage:true});
 }
 for(const width of [390,320]){
  const mobile=await browser.newContext({viewport:{width,height:width===320?568:844}});const p=await mobile.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/register.php');await p.locator('[data-neo-companion]').waitFor();
  const largeFace=await p.locator('[data-neo-companion]').boundingBox();assert(largeFace.width>180&&largeFace.height>100,'Mobile Manel starts large '+width);
  await p.locator('.neo-setup.has-studies').waitFor();
  await p.screenshot({path:path.join(artifacts,width+'-welcome.png')});await p.locator('[name=nome]').waitFor();
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Onboarding overflows '+width);
  const face=await p.locator('[data-neo-companion]').boundingBox();assert(face.x>=0&&face.y>=0&&face.x+face.width<=width,'Manel visible '+width);
  await p.locator('[name=nome]').fill('Lara');await p.locator('[name=nome]').press('Enter');await p.locator('[name=gostos]').first().waitFor();
  await p.screenshot({path:path.join(artifacts,width+'-question.png')});await mobile.close();
 }
 const legacy=await browser.newContext();const legacyPage=await legacy.newPage();await legacyPage.goto(origin+'/login.php');const token=await legacyPage.locator('[name=csrf_token]').inputValue();
 await legacyPage.request.post(origin+'/login.php',{form:{email:'legacy@example.test',senha:'Neo-test-1234',csrf_token:token}});
 await legacyPage.goto(origin+'/materias.php');assert(legacyPage.url().endsWith('/register.php'),'Legacy profile is mandatory before studies');
 assert.deepEqual(errors,[]);assert(!/Fatal error|Uncaught|PHP Warning/.test(logs),logs.slice(-4000));
 console.log('PASS: full real onboarding, validation, CSRF, reload reset, back/edit, account/profile, mandatory legacy gate, answer learning, simulations and responsive desktop/mobile.');
})().catch(async e=>{console.error(e);if(mainPage){console.error('Page:',mainPage.url());console.error((await mainPage.locator('body').innerText()).slice(-2500));await mainPage.screenshot({path:path.join(artifacts,'failure.png')});}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.kill();try{fixture('cleanup');}catch(e){console.error('Fixture cleanup:',e.message);}});
