<?php

return static function (PDO $pdo): void {
    $stmt = $pdo->prepare("
        INSERT INTO produtos
            (codigo, nome, descricao, preco_cossas, categoria, classe_visual, metadados_json, estoque, ativo, temporario, permanente, limite_por_usuario, removido_em)
        VALUES (?, ?, ?, ?, ?, ?, ?, NULL, 1, 0, 1, 1, NULL)
        ON DUPLICATE KEY UPDATE
            nome = VALUES(nome),
            descricao = VALUES(descricao),
            preco_cossas = VALUES(preco_cossas),
            categoria = VALUES(categoria),
            classe_visual = VALUES(classe_visual),
            metadados_json = VALUES(metadados_json),
            estoque = NULL,
            ativo = 1,
            temporario = 0,
            permanente = 1,
            limite_por_usuario = 1,
            removido_em = NULL
    ");

    $produtos = [
        [
            'tema_carmesim_flambler',
            'Carmesim Flambler',
            'Tema rubro com brilho quente, painéis escuros e energia de chama.',
            410,
            'tema_site',
            'theme-crimson-flambler',
            [
                'accent' => '#ff405d',
                'accent2' => '#ff9b45',
                'page_bg' => '#16050b',
                'panel_bg' => 'rgba(45, 9, 20, .94)',
                'control_bg' => 'rgba(34, 7, 16, .9)',
                'border' => 'rgba(255, 64, 93, .34)',
            ],
        ],
        [
            'tema_midas_reais',
            'Midas Reais',
            'Tema dourado real com contraste escuro e brilho de tesouro.',
            440,
            'tema_site',
            'theme-midas-royal',
            [
                'accent' => '#ffd36a',
                'accent2' => '#fff0a6',
                'page_bg' => '#141006',
                'panel_bg' => 'rgba(42, 33, 10, .94)',
                'control_bg' => 'rgba(31, 24, 8, .9)',
                'border' => 'rgba(255, 211, 106, .34)',
            ],
        ],
        [
            'tema_erupcao',
            'Erupção',
            'Tema vulcânico com laranja intenso, vermelho profundo e fundo liso quente.',
            430,
            'tema_site',
            'theme-eruption',
            [
                'accent' => '#ff6b1a',
                'accent2' => '#ffcc4d',
                'page_bg' => '#170806',
                'panel_bg' => 'rgba(47, 17, 9, .94)',
                'control_bg' => 'rgba(35, 12, 7, .9)',
                'border' => 'rgba(255, 107, 26, .34)',
            ],
        ],
        [
            'tema_kawaii',
            'Kawaii!',
            'Tema rosa fofo com brilho suave e bolhas claras.',
            390,
            'tema_site',
            'theme-kawaii',
            [
                'accent' => '#ff79c8',
                'accent2' => '#ffc1ea',
                'page_bg' => '#18091a',
                'panel_bg' => 'rgba(48, 16, 48, .94)',
                'control_bg' => 'rgba(35, 12, 37, .9)',
                'border' => 'rgba(255, 121, 200, .34)',
            ],
        ],
        [
            'tema_chuva_roxa',
            'Chuva Roxa',
            'Tema violeta chuvoso, com destaque roxo e clima noturno.',
            420,
            'tema_site',
            'theme-purple-rain',
            [
                'accent' => '#9b6bff',
                'accent2' => '#ce8cff',
                'page_bg' => '#0d071a',
                'panel_bg' => 'rgba(26, 14, 54, .94)',
                'control_bg' => 'rgba(18, 10, 42, .9)',
                'border' => 'rgba(155, 107, 255, .34)',
            ],
        ],
        [
            'manel_lumi',
            'Lumi',
            'Transforma o assistente em Lumi, com cílios, brilho violeta e jeito calmo e paciente.',
            320,
            'skin_manel',
            'manel-lumi',
            [
                'manel_name' => 'Lumi',
                'manel_color' => '#b58cff',
                'manel_glow' => 'rgba(181, 140, 255, .48)',
                'manel_variant' => 'lumi',
                'manel_personality' => 'calma',
            ],
        ],
        [
            'manel_karol',
            'Karol',
            'Skin rosa com cílios e personalidade fria, direta e brincalhona.',
            340,
            'skin_manel',
            'manel-karol',
            [
                'manel_name' => 'Karol',
                'manel_color' => '#ff72c8',
                'manel_glow' => 'rgba(255, 114, 200, .48)',
                'manel_variant' => 'karol',
                'manel_personality' => 'fria_brincalhona',
            ],
        ],
        [
            'manel_ravir',
            'Ravir',
            'Skin amarela com óculos e jeito nerdzão, curioso e explicativo.',
            350,
            'skin_manel',
            'manel-ravir',
            [
                'manel_name' => 'Ravir',
                'manel_color' => '#ffd84a',
                'manel_glow' => 'rgba(255, 216, 74, .48)',
                'manel_variant' => 'ravir',
                'manel_personality' => 'nerd',
            ],
        ],
        [
            'manel_ruan',
            'Ruan',
            'Skin preta com sardas e uma personalidade rockeira, brincalhona e malandra.',
            350,
            'skin_manel',
            'manel-ruan',
            [
                'manel_name' => 'Ruan',
                'manel_color' => '#10131c',
                'manel_glow' => 'rgba(210, 220, 255, .34)',
                'manel_variant' => 'ruan',
                'manel_personality' => 'rockeiro',
            ],
        ],
        [
            'manel_joshua',
            'Joshua',
            'Skin vermelha com energia agressiva, alegre e direta.',
            330,
            'skin_manel',
            'manel-joshua',
            [
                'manel_name' => 'Joshua',
                'manel_color' => '#ff313d',
                'manel_glow' => 'rgba(255, 49, 61, .48)',
                'manel_variant' => 'joshua',
                'manel_personality' => 'agressivo_alegre',
            ],
        ],
        [
            'nome_carmesim',
            'Nome Carmesim',
            'Deixa seu nome com destaque vermelho profundo.',
            180,
            'cor_nome',
            'name-crimson',
            ['name_color' => '#ff405d'],
        ],
        [
            'nome_rosa_pop',
            'Nome Rosa Pop',
            'Deixa seu nome em rosa vibrante.',
            180,
            'cor_nome',
            'name-pink',
            ['name_color' => '#ff72c8'],
        ],
        [
            'nome_ciano',
            'Nome Ciano',
            'Deixa seu nome em ciano luminoso.',
            180,
            'cor_nome',
            'name-cyan',
            ['name_color' => '#55d9ff'],
        ],
        [
            'nome_esmeralda',
            'Nome Esmeralda',
            'Deixa seu nome em verde esmeralda.',
            180,
            'cor_nome',
            'name-emerald',
            ['name_color' => '#45e08f'],
        ],
        [
            'nome_roxo_chuva',
            'Nome Roxo Chuva',
            'Deixa seu nome em roxo brilhante.',
            180,
            'cor_nome',
            'name-purple',
            ['name_color' => '#b27cff'],
        ],
        [
            'nome_neve',
            'Nome Neve',
            'Deixa seu nome branco e limpo, com contraste forte.',
            190,
            'cor_nome',
            'name-snow',
            ['name_color' => '#f4f7ff'],
        ],
        [
            'nome_sombra',
            'Nome Sombra',
            'Deixa seu nome em cinza escuro metálico.',
            190,
            'cor_nome',
            'name-shadow',
            ['name_color' => '#9aa3b8'],
        ],
    ];

    foreach ($produtos as [$codigo, $nome, $descricao, $preco, $categoria, $classe, $metadados]) {
        $stmt->execute([
            $codigo,
            $nome,
            $descricao,
            $preco,
            $categoria,
            $classe,
            json_encode($metadados, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
        ]);
    }
};
